-- Echo Node: Backfill nodes table columns (PostgreSQL)
-- Idempotent migrations for nodes table columns that may not exist
-- in databases created by earlier versions.

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT 'EchoNode';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT 'anonymous';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS peer_id TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS public_key TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'offline';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_seen_at TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS uptime DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS latency DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS bandwidth_used DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS earnings DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS packet_loss DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_updated TIMESTAMPTZ;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_ip TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS services JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS uptime_pct DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS avg_latency_ms DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS bandwidth_down_mbps DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS bandwidth_up_mbps DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS packet_loss_pct DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS quality_score DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS trust_score DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS sessions_count BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS earnings_usd DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS reported_upload_cap_mbps DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS reported_download_cap_mbps DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS supported_encryption TEXT DEFAULT 'noise-xx';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
